FROM microsoft/dotnet:2.1-sdk
WORKDIR /var/www/
ENV ASPNETCORE_URLS=http://+:5000
ENV NUGET_XMLDOC_MODE skip
WORKDIR /vsdbg
EXPOSE 5000
RUN apt-get update && apt-get install -y \
    && apt-get install tesseract-ocr -y \
    && apt-get install tesseract-ocr-por \
    && apt-get install curl unzip -y \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

RUN mkdir /app
WORKDIR /app

COPY *.csproj /app
RUN dotnet restore

COPY . /app
# RUN dotnet publish -c Debug -o out

# Kick off a container just to wait debugger to attach and run the app
CMD [ "dotnet", "buildx" ]
ENTRYPOINT ["/bin/bash", "-c", "sleep infinity"]