
FROM microsoft/dotnet:2.1-sdk
WORKDIR /var/www/
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000
RUN apt-get update && apt-get install -y && \
    apt-get install tesseract-ocr -y && \
    apt-get install tesseract-ocr-por